import re
import json as json_module
from pathlib import Path
from tools.gemini import ask
from tools.git_tools import get_diff, create_branch
from database import get_conn, log


def read_file(repo_path: str, filename: str) -> str:
    p = Path(repo_path) / filename
    if p.exists():
        return p.read_text(encoding="utf-8", errors="ignore")
    return ""


def write_file(repo_path: str, filename: str, content: str):
    p = Path(repo_path) / filename
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")


def extract_code(response: str, filename: str) -> str:
    response = response.strip()

    # Match any ```language\n...\n``` block, language tag optional
    pattern = r"```[a-zA-Z]*\n(.*?)\n?```"
    match = re.search(pattern, response, re.DOTALL)
    if match:
        return match.group(1).strip()

    # If response starts with ``` but regex above didn't catch it cleanly,
    # strip leading/trailing fence lines manually
    lines = response.split("\n")
    if lines and lines[0].strip().startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]

    cleaned = "\n".join(lines).strip()
    return cleaned


def run_coder(repo_knowledge: dict, plan: dict) -> dict:
    print(f"\n[Stage 3] Coding with Gemini...")

    repo_path = repo_knowledge["local_path"]
    affected_files = plan["affected_files"]
    aider_task = plan["aider_task"]
    branch_name = plan["branch_name"]
    contribution_id = plan["contribution_id"]

    # Create git branch
    try:
        create_branch(repo_path, branch_name)
    except Exception as e:
        print(f"  Branch already exists, continuing: {e}")

    files_changed = []

    for filename in affected_files:
        print(f"\n  Working on: {filename}")

    # Never let the LLM hand-edit lock files — they must be machine-generated
        lock_files = ("package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "Cargo.lock")
        if filename.endswith(lock_files) or filename in lock_files:
            print(f"  SKIPPED: {filename} is a lock file — must be regenerated by the package manager, not edited by AI")
            continue

        # Read current file content
        current_content = read_file(repo_path, filename)

        if not current_content:
            print(f"  File not found: {filename} — skipping")
            continue

        # Ask Gemini to modify the file
        prompt = f"""You are a software engineer implementing a change in a {repo_knowledge['framework']} project.

TASK:
{aider_task}

CURRENT FILE: {filename}
{current_content[:6000]}

Instructions:
- Implement the requested change in this file
- Keep all existing functionality intact
- Match the existing code style exactly
- Make minimal, clean changes
- Return ONLY the complete updated file content inside a single code block
- Do not include explanations, headers, or any text outside the code block
- Do not wrap the code block in extra backticks or repeat the fence

Return the complete updated {filename} content:"""

        print(f"  Asking Gemini to implement changes...")
        response = ask(prompt)

        # Extract the code from response
        new_content = extract_code(response, filename)

        if not new_content or len(new_content) < 20:
            print(f"  Gemini returned empty response for {filename} — skipping")
            continue

        if new_content == current_content:
            print(f"  No changes made to {filename}")
            continue

        # Safety check: never write a broken JSON file
        if filename.endswith(".json"):
            try:
                json_module.loads(new_content)
            except json_module.JSONDecodeError as e:
                print(f"  REJECTED: Generated {filename} is not valid JSON ({e})")
                print(f"  Skipping this file to avoid breaking the build.")
                continue

        # Safety check: reject if stray code fences leaked through
        if "```" in new_content:
            print(f"  REJECTED: {filename} still contains markdown fences after extraction")
            print(f"  Skipping this file to avoid corrupting it.")
            continue

        # Safety check: reject suspicious content loss (likely truncation)
        if filename.endswith((".md", ".txt", ".rst")):
            if len(current_content) > 500 and len(new_content) < len(current_content) * 0.5:
                print(f"  REJECTED: {filename} shrank from {len(current_content)} to {len(new_content)} chars")
                print(f"  This looks like content was accidentally deleted, not edited.")
                continue


        # Write the updated file
        write_file(repo_path, filename, new_content)
        files_changed.append(filename)
        print(f"  Updated {filename} ({len(new_content)} chars)")

    # Get the full diff
    diff = get_diff(repo_path)

    if diff:
        print(f"\n  Total diff: {len(diff)} chars across {len(files_changed)} files")
    else:
        print("\n  No changes detected in diff")

    code_result = {
        "success": len(diff) > 0,
        "diff": diff,
        "branch_name": branch_name,
        "affected_files": affected_files,
        "files_changed": files_changed,
        "had_changes": len(diff) > 0
    }

    # Save to DB
    conn = get_conn()
    conn.execute(
        "UPDATE contributions SET diff = ?, status = ? WHERE id = ?",
        (diff, "coded", contribution_id)
    )
    conn.commit()
    conn.close()

    log(contribution_id, "coder", f"Done. Changed {len(files_changed)} files.")

    return code_result


if __name__ == "__main__":
    # Standalone test of Stage 3 only — not used when running main.py
    from pipeline.understander import understand_repo
    from pipeline.analyser import analyse

    test_repo_url = "https://github.com/vv-verse/KrishiSetu"

    repo = understand_repo(test_repo_url)
    plan = analyse(
        repo,
        mode="feature",
        user_input="Add a loading spinner to the submit button"
    )
    result = run_coder(repo, plan)

    print(f"\n--- CODER RESULT ---")
    print(f"Success      : {result['success']}")
    print(f"Files changed: {result['files_changed']}")
    print(f"Diff preview :\n{result['diff'][:600]}")